---
driver:
  name: vagrant

driver_config:
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
    network:
    - ["private_network", {ip: "33.33.33.1"}]
    - ["forwarded_port", {guest: 8080, host: 8080}]
  - name: centos-6.5
    run_list:
    - recipe[yum]
    network:
    - ["private_network", {ip: "33.33.33.2"}]
    - ["forwarded_port", {guest: 8080, host: 8081}]

suites:
  - name: jenkins
    run_list:
      - recipe[pipeline::jenkins]
      - recipe[chef-zero]
      - recipe[pipeline::knife]
      - recipe[pipeline::berkshelf]
    attributes:
      chef-zero:
        start: true
