---
driver:
  name: vagrant

driver_config:
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
    network:
    - ["forwarded_port", {guest: 8080, host: 8080}]
  - name: centos-6.5
    run_list:
      - recipe[yum]
    network:
    - ["forwarded_port", {guest: 8080, host: 8081}]

suites:
  - name: jenkins
    run_list:
      - recipe[git]
      - recipe[build-essential]
      - recipe[emacs]
      - recipe[pipeline::jenkins]
      - recipe[chef-zero]
      - recipe[pipeline::knife]
      - recipe[pipeline::berkshelf]
      - recipe[pipeline::cookbooks]
    attributes:
      chef-zero:
        start: true
      build-essential:
        compile_time: true
